export type UserProfile = { id: string; authId?: string; username: string; name: string; email: string; phone?: string; dob?: string; gender?: string; avatarUrl?: string | null; city?: string | null; state?: string | null; pincode?: string | null; preferredSport?: string | null; address?: string | null };
export type Turf = {
  id: string;
  name: string;
  city?: string;
  address?: string;
  pincode?: string;
  turfSize?: string;
  sportsType?: string;
  images?: string[];
  entranceUrl?: string;
  groundDayUrl?: string;
  groundNightUrl?: string;
  videoUrl?: string | null;
  rating?: number;
  reviewCount?: number;
  dayPrice?: number;
  nightPrice?: number;
  weekdayDayPrice?: number;
  weekdayNightPrice?: number;
  weekendDayPrice?: number;
  weekendNightPrice?: number;
  amenities?: string[];
  description?: string;
  openTime?: string;
  closeTime?: string;
  floodLights?: boolean;
  parking?: boolean;
  washroom?: boolean;
  changingRoom?: boolean;
  drinkingWater?: boolean;
  seatingArea?: boolean;
  cafeteria?: boolean;
  paymentPreferences?: string[];
  minSlotDurationMins?: number;
  bookingApprovalType?: string;
  cancellationAllowedBeforeHours?: number;
  cancellationRefundPercentage?: number;
  owner?: {
    name: string;
    contactNumber: string;
  };
  rules?: string[];
  customerReviews?: {
    id: string;
    reviewerName: string;
    rating: number;
    comment: string | null;
    createdAt: string;
  }[];
};
export type BookingStatus = "PENDING" | "CONFIRMED" | "COMPLETED" | "CANCELLED" | "NO_SHOW";
export type PaymentStatus = "PENDING" | "SUCCESS" | "FAILED" | "REFUNDED";
export type PaymentType = "FULL_ONLINE" | "HALF_ONLINE_HALF_CASH" | "FULL_CASH";
export type Booking = { id: string; displayId: string; turfId?: string; bookingDate: string; startTime: string; endTime: string; durationMins?: number; bookingStatus: BookingStatus; paymentStatus: PaymentStatus; paymentType?: PaymentType; amount: number; depositAmount?: number; amountToPay: number; remainingAmount?: number; checkInPin?: string | null; qrCode?: string | null; turf?: Turf };
export type Notification = { id: string; title: string; body: string; type?: string; isRead: boolean; createdAt: string };
